name: Docker Image CI

on:
  push:
    branches: [ build_and_test ]

jobs:

  build-test-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Build & Push
      uses: mr-smithers-excellent/docker-build-push@v3.0
      with:
        image: krishbharath/mkdocs_image
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Display the path and contents
      run: |
        echo $PATH
        ls -lsa
      shell: bash

    - name: list containers and images
      run: |
        docker images
        docker ps -a

    services:
      mkdocs:
        image: mkdocs_image
        ports:
          - 8000:8000
        volumes:
        - $GITHUB_WORKSPACE/mkdocs_docker/:/shared_dir

    # - name: Test image
    #   run: |
    #     docker run --name mkdocs_container -d --rm -v $GITHUB_WORKSPACE/mkdocs_docker/:/shared_dir -p 8000:8000 mkdocs_image serve
    #     var="$(curl localhost:8000 2>/dev/null)" && if echo "$var" | grep 'Welcome to MkDocs'; then   echo "It works"; else fail; fi
